transformsTrain: []
transformsTest: []
transformsFinal: []

loss: "NLLPriorLoss"
lossKwargs: {}

metricsTest:
  - type: NLLPrior
    kwargs: {}
  - type: Dummy
    kwargs: {}

batchSize: 1024

optimizer: "AdamW"
optimizerKwargs:
  lr: 0.05
  weight_decay: 0.01

numEpochs: 100

enableAMP: False

lrSchedulers: []
