network:
  name: "ffjord_l2_hm10_f10_softplus"
  dataset: "Hepmass"
  outputSize: 21

training:
  transformsTrain: []
  transformsTest: []
  transformsFinal: []

  loss: "NLLNatsLoss"
  lossKwargs: {}

  metricsTest:
    - type: NLLNats
      kwargs: {}
    - type: Dummy
      kwargs: {}

  batchSize: 10000

  optimizer: "Adam"
  optimizerKwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-6

  numEpochs: 400
  earlyStopEpoch: 0

  enableAMP: False

  lrSchedulers:
    - type: MultiStepLR
      stepKwargs: { milestones: [325, 375] }
      kwargs: { gamma: 0.1 }

file: "paper/node/param/directories.yaml"

retraining:
  startEpoch: 0
  numEpochs: 300
  earlyStopEpoch: 0

  lrSchedulers:
    - type: MultiStepLR
      stepKwargs: { milestones: [250, 295] }
      kwargs: { gamma: 0.1 }

experiments:
  methods:
    - "ThresNet"
    - "FilterThresNet"
  mode: "cascade"

  numRepetitions: 1
  numNets: 1

  plotting:
    minVal: 0.02
    maxVal: 0.85

  spacing:
    - type: "geometric"
      numIntervals: 12
      maxVal: 0.80
      minVal: 0.05

  retrainIterations: -1
