network:
  name: "ffjord_multiscale_cifar"
  dataset: "CIFAR10"
  outputSize: 10

training:
  transformsTrain:
    - type: RandomHorizontalFlip
      kwargs: {}
  transformsTest: []
  transformsFinal:
    - type: Resize
      kwargs: { size: 32 }
    - type: ToTensor
      kwargs: {}
    - type: RandomNoise
      kwargs: { "normalization": 255.0 }

  loss: "NLLBitsLoss"
  lossKwargs: {}

  metricsTest:
    - type: NLLBits
      kwargs: {}
    - type: Dummy
      kwargs: {}

  batchSize: 200 # don't change that since it's hard-coded

  optimizer: "Adam"
  optimizerKwargs:
    lr: 1.0e-3
    weight_decay: 0.0

  numEpochs: 50
  earlyStopEpoch: 0
  enableAMP: False

  lrSchedulers:
    - type: MultiStepLR
      stepKwargs: { milestones: [45] }
      kwargs: { gamma: 0.1 }

file: "paper/node/param/directories.yaml"

retraining:
  startEpoch: 0

experiments:
  methods:
    - "ThresNet"
    - "FilterThresNet"
  mode: "cascade"

  numRepetitions: 1
  numNets: 1

  plotting:
    minVal: 0.02
    maxVal: 0.85

  spacing:
    - type: "geometric"
      numIntervals: 12
      maxVal: 0.80
      minVal: 0.05

  retrainIterations: -1
